<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:tns="urn://co-opbank.co.ke/CommonServices/TS/Util/Sub/SendExceptionEvent" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsd1="urn://co-opbank.co.ke/CommonServices/Message/TS/Util/Sub/SendExceptionEvent" name="SendExceptionEvent" targetNamespace="urn://co-opbank.co.ke/CommonServices/TS/Util/Sub/SendExceptionEvent">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="urn://co-opbank.co.ke/CommonServices/Message/TS/Util/Sub/SendExceptionEvent" schemaLocation="../../../../../Schemas/CommonServices/Message/TS/Util/Sub/SendExceptionEvent.xsd">
			</xsd:import>
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="SendExceptionEventRequest">
		<wsdl:part element="xsd1:SendExceptionEventRequest" name="parameters"/>
	</wsdl:message>

    <wsdl:message name="operationRequest">
    <wsdl:part element="xsd1:operationRequest" name="parameters"/>
  </wsdl:message>
    <wsdl:portType name="SendExceptionEvent">
		<wsdl:operation name="SendExceptionEvent">
			<wsdl:input message="tns:SendExceptionEventRequest"/>
		</wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
